### ISSUE TITLE
[Enhancement] [Filter Manipulation] Add more filter customization options to let users further differentiate our app's filter changes

### ISSUE THREAD

**Issue by SirTwsted** [ChaosRecipeEnhancer/EnhancePoEApp#253]
There is a huge problem with this that I noticed, maybe im missing something but.
If you have to colorize the items, wouldnt that confuse the FilterBlade Filters people
have downloaded already?

Maybe this tool should put something like a Diamond Icon. Or even the icon for the
Choas Orb itself on the item banner, so people know its for the Tool,
while also not messing with the FilterBlades Filter settings and colors people have already assigned to their items .....

Just a thought 👋🤡👍

**Comment by mikedorsi** [comment]
This would be a huge enhancement to the tool.  I second this opinion.  I've personally already created my own loot filter around the chaos recipe.  The main difference is PoeEnhance can tell me if I need the item or not by directly putting an icon next to the text name or only changing the border color or background color for example.

**Comment by Davst** [comment]
The real MVP move here would be if Filterblade would somehow allow you to tag a section and that the tool could show/hide that section. This has been accomplised before with some start and end tagging in the filters.. which tbh is a mess sinnce you have to edit it after downloading.

Not sure if you could speak to Neversink and somehow have something like this added as a custom feature selectable in Neversink.. that way the config should persist between updates with the tool just switching that on and off.

Until then, the current method is pretty good since it does infact override the normal logic of the filter which I appriciate as I can run on Very strict and still get items.

Having more selections for the look and feel of the items wouldn't hurt.. like sound, iconn Text, frame, bg and fg. Would be cool with a few preset looks as well.

**Comment by Davst** [comment]
Btw could we renname this to something more descriptive of the discussion?

**Comment by HiMarioLopez** [comment]
Would be a neat thing to add.

Filter syntax: https://www.pathofexile.com/item-filter/about

**Comment by HiMarioLopez** [comment]
done

https://github.com/ChaosRecipeEnhancer/ChaosRecipeEnhancer/releases/tag/3.25.0002-beta

full release next week thanks for your patience
