### ISSUE TITLE
Errors while installing 

### ISSUE THREAD

**Issue by empoliyis** [ChaosRecipeEnhancer/EnhancePoEApp#328]
hello i'm getting these 2 errors, error code 2503 and 2502 when installing the program
![image](https://user-images.githubusercontent.com/93097732/162901496-9291b7da-8e6a-42a7-a6fc-604d33040097.png)
![image](https://user-images.githubusercontent.com/93097732/162901564-37dd178c-0b08-480d-9434-f5f55cfb70a4.png)

**Comment by HiMarioLopez** [comment]
"This error is mostly due to permissions issue with the Temp folder of Windows which can be usually found in C:\Windows\Temp. While the issue is not limited to permissions issue as sometimes virus or malware, incorrect registry, corrupt Windows Installer, incompatible 3rd party programs etc can also cause the error 2502/2503. To Fix this error, please refer to the below-listed troubleshooting solutions."

Hmm let's try running installer with elevated permissions to start off.

Here's a link to a post of a piece of software that uses the same installer libraries we use in our app. The solutions listed here will surely fix the install.

https://kb.foxitsoftware.com/hc/en-us/articles/360040660391-Fix-Error-2502-and-2503-while-installing-or-uninstalling#:~:text=The%20error%20code%202503.,a%20problem%20with%20this%20package.

**Comment by HiMarioLopez** [comment]
Going to be closing this out since it's a stale issue now. Please go ahead and open a new issue if you have any other issues, thanks!
